### ISSUE TITLE
cdn_repo: better error on missing variant

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#257]
When the Ansible `errata_tool_cdn_repo` play references a variant that does not exist, we crash with `ValueError`:

```
Traceback (most recent call last):
  File "modules/errata_tool_cdn_repo.py", line 693, in <module>
  File "modules/errata_tool_cdn_repo.py", line 689, in main
  File "modules/errata_tool_cdn_repo.py", line 683, in run_module
  File "modules/errata_tool_cdn_repo.py", line 618, in ensure_cdn_repo
  File "modules/errata_tool_cdn_repo.py", line 310, in create_cdn_repo
ValueError: {"errors":{"variants":["cannot find variant: 7Base-3SCALE-2.12-dev"]}}
```

It would be clearer if we raised a custom `VariantNotFoundError` and then caught that in `run_module()`, similar to #231

**Comment by ktdreyer** [comment]
Exact error to scrape in `app/controllers/api/v1/cdn_repos_controller.rb`:

```ruby
raise DetailedArgumentError.new(:variants => "cannot find #{'variant'.pluralize(missing.count)}: #{missing.join(', ')}")
```
