### ISSUE TITLE
JSONDecodeError in create_product()

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/errata-tool-ansible#295]
Jakub Micanek (Vitals team) found the following error in the latest errata-tool-ansible code:
```
modules/errata_tool_product.py\", line 392, in <module>
modules/errata_tool_product.py\", line 388, in main
modules/errata_tool_product.py\", line 349, in run_module
modules/errata_tool_product.py\", line 299, in ensure_product
modules/errata_tool_product.py\", line 245, in create_product
module_utils/common_errata_tool.py\", line 12, in __init__
File \"/usr/local/lib/python3.8/site-packages/requests/models.py\", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 11 column 1 (char 10)
```

I don't have the full module parameters yet, but here are some clues from the loop vars in the logs:

```
'name': 'Release End2End Test',
'short_name': 'release-e2e-test',
'description': 'Used by Vitals',
'push_targets': ['cdn_stage', 'cdn_docker_stage', 'cdn_docker', 'cdn'],
```

**Comment by kubasikus** [comment]
Hey @ktdreyer ,
We're using containerized errata-rails v4.18. 

Here's the full trace, running from local:
The full traceback is:
```
Traceback (most recent call last):
  File "/home/jmicanek/.local/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 11 column 1 (char 10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py", line 107, in <module>
    _ansiballz_main()
  File "/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.errata_tool_product', init_globals=dict(_module_fqn='ansible.modules.errata_tool_product', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py", line 392, in <module>
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py", line 388, in main
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py", line 349, in run_module
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py", line 308, in ensure_product
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py", line 272, in edit_product
  File "/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/module_utils/common_errata_tool.py", line 12, in __init__
  File "/home/jmicanek/.local/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 11 column 1 (char 10)
failed: [localhost] (item={'name': 'Release End2End Test', 'short_name': 'release-e2e-test', 'description': 'Used by Vitals', 'push_targets': ['cdn_stage', 'cdn_docker_stage', 'cdn_docker', 'cdn']}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "description": "Used by Vitals",
        "name": "Release End2End Test",
        "push_targets": [
            "cdn_stage",
            "cdn_docker_stage",
            "cdn_docker",
            "cdn"
        ],
        "short_name": "release-e2e-test"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/jmicanek/.local/lib/python3.11/site-packages/requests/models.py\", line 971, in json\n    return complexjson.loads(self.text, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/__init__.py\", line 514, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/decoder.py\", line 386, in decode\n    obj, end = self.raw_decode(s)\n               ^^^^^^^^^^^^^^^^^^\n  File \"/home/jmicanek/.local/lib/python3.11/site-packages/simplejson/decoder.py\", line 416, in raw_decode\n    return self.scan_once(s, idx=_w(s, idx).end())\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nsimplejson.errors.JSONDecodeError: Expecting value: line 11 column 1 (char 10)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/jmicanek/.ansible/tmp/ansible-tmp-1693238497.5997257-885012-244523915274321/AnsiballZ_errata_tool_product.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.errata_tool_product', init_globals=dict(_module_fqn='ansible.modules.errata_tool_product', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py\", line 392, in <module>\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py\", line 388, in main\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py\", line 349, in run_module\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py\", line 308, in ensure_product\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/modules/errata_tool_product.py\", line 272, in edit_product\n  File \"/tmp/ansible_errata_tool_product_payload_6i9hge7m/ansible_errata_tool_product_payload.zip/ansible/module_utils/common_errata_tool.py\", line 12, in __init__\n  File \"/home/jmicanek/.local/lib/python3.11/site-packages/requests/models.py\", line 975, in json\n    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)\nrequests.exceptions.JSONDecodeError: Expecting value: line 11 column 1 (char 10)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

```

**Comment by ktdreyer** [comment]
PR #293 uses the `/api/v1/products` REST API that the Errata Tool developers introduced in CWFENGINE-927 and shipped in errata-rails 4.24-0. You'll need to update to 4.24 to use `errata_tool_product` now.

Sounds like the errata-rails server is returning non-JSON because PUT and POST are not yet supported on `/api/v1/products`, and when we try to raise that error text to the user, the `ErrataToolError` class does not properly handle the non-JSON response (https://github.com/ktdreyer/errata-tool-ansible/issues/296).

**Comment by hluk** [comment]
Hmm, I wonder if `Accept: application/json` header should be always set.

**Comment by ktdreyer** [comment]
> Hmm, I wonder if Accept: application/json header should be always set.

Good idea. I have hit so many errors that I'm not sure it would cover all of them, but even if we reduce our changes by a little bit, that's a win.

I'm thinking of setting `self.session.headers['Accept'] = 'application/json'` in `common_errata_tool.Client`, so that it will apply everywhere, then override that in the single place where we need HTML, `WorkflowRulesScraper`'s `_get_page_content()` method.
